#ifndef CONTROLS_H
#define CONTROLS_H

#include "riv.h"

enum {
    CONTROL_TECHNICAL_VIEW = RIV_GAMEPAD_R1,
    CONTROL_TECHNICAL_PREVIOUS_SPAN = RIV_GAMEPAD_L2,
    CONTROL_TECHNICAL_NEXT_SPAN = RIV_GAMEPAD_R2,
    CONTROL_CHEAT_NEXT_LEVEL = RIV_GAMEPAD_R3
};

#endif
